name: seq2seq_base

encoder:
  _target_: src.models.encoder.Encoder
  vocab_size: null
  embedding_dim: 256
  hidden_dim: 512
  num_layers: 2
  dropout: 0.1
  bidirectional: true

decoder:
  _target_: src.models.decoder.Decoder
  vocab_size: null
  embedding_dim: 256
  hidden_dim: 1024
  num_layers: 2
  dropout: 0.1
  attention: true

seq2seq:
  _target_: src.models.seq2seq.Seq2Seq
  encoder: ${model.encoder}
  decoder: ${model.decoder}
  teacher_forcing_ratio: 0.5
  pad_token_id: null