name: transformer


model_info:
  _target_: src.models.transformer.Transformer
  d_model: 512
  nhead: 8
  num_encoder_layers: 4
  num_decoder_layers: 4
  dim_feedforward: 1024
  dropout: 0.1
  max_seq_length: ${data.tokenizer.max_length}
