models:
  tiny:
    title: "Tiny Seq2Seq"
    name: "tiny_seq2seq"
    checkpoint_dir: "tiny_seq2seq"
    max_length: 32
    description: "маленькая модель Tiny Seq2Seq"
  
  base:
    title: "Base Seq2Seq"
    name: "seq2seq"
    checkpoint_dir: "seq2seq_base"
    max_length: 128
    description: "Базовая Seq2Seq. Есть шанс что перевод будет немного осмысленным"
  
  transformer:
    title: "transformer"
    name: "transformer"
    checkpoint_dir: "transformer"
    max_length: 64
    description: "Трансформер"

base_ml_config: ../config

server:
  host: localhost
  port: 8000
  reload: true
